image: registry.ide3.de/docker/gcc-cmake

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - cmake .
    - cmake --build .
    - date
  artifacts:
    paths:
      - ./liste_v1

test-job1:
  stage: test
  script:
    - date
    - ls -al
    - ./liste_v1
