name: Build and Test C Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get install build-essential
      
    - name: Go To folder
      run: cd studies/Testing/listeactiontest

    - name: Build C code
      run: |
        gcc -o main test.c

    - name: Run tests
      run: |
        ./main
